### ISSUE TITLE
[init] 초기 프로젝트 설정 진행

### ISSUE THREAD

**Issue by yeeun0702** [SOPT-all/35-APPJAM-SERVER-BBANGZIP#1]
## Issue 📌

초기 프로젝트에 대한 세팅 작업들을 진행할 예정입니다.
해당 작업에 대해서는 devlop에 올리지 않고 main 브랜치에 바로 적용시킬 예정입니다.

## Todo ✔️

- [x]  Spring Initializer 를 통한 작업 진행
    - [x]  .gitignore 세팅
    - [x]  library setting(lombok,spring-boot-starter-web만 일단 추가)
- [x] 수동배포 (ec2, rds) 설정 진행
